name: sensation
description: "Sensation is a Flutter plugin that enables a reliable and lightweight gesture detector on widgets."
version: 0.0.3
auther: Ta-Yi Cheng<admin@tranquility.tech>
homepage: https://www.tranquility.tech/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tech.tranquility.sensation
        pluginClass: Sensation
      ios:
        pluginClass: Sensation